apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
  labels:
    app: message-consumer
spec:
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        app: message-consumer
    spec:
      containers:
        - name: message-consumer
          image: docker.io/abhi2495/message-consumer:latest
      imagePullSecrets:
        - name: docker-registry-credentials