apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-msgs
spec:
  secretTargetRef:
    - parameter: connection
      name: secrets-msg-management
      key: servicebus-msg-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-msg-management
  labels:
    app: message-consumer
data:
  servicebus-msg-connectionstring: <base64encoded-connection-string>
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: message-consumer-scaler
spec:
  scaleTargetRef:
    name: message-consumer
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: item-ingestion-queue
        namespace: lse-keda-poc
        messageCount: "200"
      authenticationRef:
        name: trigger-auth-service-bus-msgs